# build environment
FROM node:13 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN yarn install
COPY . /app

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL ${REACT_APP_BACKEND_URL}
ARG REACT_APP_SHOPIFY_CLIENT_ID
ENV REACT_APP_SHOPIFY_CLIENT_ID ${REACT_APP_SHOPIFY_CLIENT_ID}
ARG REACT_APP_SHOPIFY_REDIRECT_URL
ENV REACT_APP_SHOPIFY_REDIRECT_URL ${REACT_APP_SHOPIFY_REDIRECT_URL}
ARG REACT_APP_GOOGLE_CLIENT_ID
ENV REACT_APP_GOOGLE_CLIENT_ID ${REACT_APP_GOOGLE_CLIENT_ID}
ARG REACT_APP_RECAPTCHA_SITE_KEY
ENV REACT_APP_RECAPTCHA_SITE_KEY ${REACT_APP_RECAPTCHA_SITE_KEY}
ARG REACT_APP_HOTJAR_SITE_ID
ENV REACT_APP_HOTJAR_SITE_ID ${REACT_APP_HOTJAR_SITE_ID}
ARG REACT_APP_HOTJAR_SERVER
ENV REACT_APP_HOTJAR_SERVER ${REACT_APP_HOTJAR_SERVER}
ARG REACT_APP_FRESHCHAT_TOKEN
ENV REACT_APP_FRESHCHAT_TOKEN ${REACT_APP_FRESHCHAT_TOKEN}
ARG REACT_APP_FRESHCHAT_HOST
ENV REACT_APP_FRESHCHAT_HOST ${REACT_APP_FRESHCHAT_HOST}

INLINE_RUNTIME_CHUNK=false RUN yarn build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
