import { getReactEnv } from '../services/env/getEnv'

const basePath = getReactEnv('USER_BASE_PATH')

const Paths = {
    HomePage: '/',
    UserPage: `${basePath}`,
    NewProduct: `/buyer/products/design`,
    ListProductsByShop: (shopId) => `${basePath}/store/${shopId || ':shopId'}/list`,
    ListProducts: `${basePath}/products`,
    ListShop: () => `${basePath}/stores`,
    ShopSetting: (shopId) => `${basePath}/stores/${shopId || ':shopId'}/setting`,
    ProductDetail: (productId) => `${basePath}/products/${productId || ':productId'}`,
    EcommerceProductDetail: (ecommerceProductId) => `${basePath}/products/unsync/${ecommerceProductId || ':productId'}`,
    Orders: `${basePath}/orders`,
    OrderDetail: (orderId) => `${basePath}/orders/${orderId || ':id'}`,
    Support: `${basePath}/support/`,
    TicketDetail: (ticketId) => `${basePath}/support/${ticketId || ':id'}`,
    Catalog: `${basePath}/catalog`,
    Login: '/login',
    TokenLogin: '/token-login',
    Register: '/register',
    ShopifyAuth: '/auth/spf',
    PayoneerActivate: '/payoneer/activate',
    Billings: `${basePath}/billings/`,
    InvoiceList: `${basePath}/billings`,
    InvoiceDetail: (invoiceId) => `${basePath}/billings/${invoiceId || ':invoiceId'}`,
    PaymentManager: `${basePath}/payments`,
    Artworks: `${basePath}/artworks`,
    ArtworkUpdate: (id) => `${basePath}/artwork/update/${id || ':id'}`,
    Profile: `${basePath}/profile`,
    Dashboard: `${basePath}/dashboard`,
    Settings: `${basePath}/settings`,
    DuplicateProduct: (productId) => `${basePath}/duplicate/${productId || ':productId'}`,
    AccountActivation: (uid, token) => `/account-activation/${uid || ':uid'}/${token || ':token'}`,
    ForgotPassword: `/forgot-password`,
    ResetPassword: (uid, token) => `/reset-password/${uid || ':uid'}/${token || ':token'}`,
    NewOrder: `${basePath}/orders/new`,
    SecurityAccessWarning: '/security-access-warning',
    SecurityOpenFullsiteWarning: '/security-fullsite-warning',
    ShopAccessWarning: '/shop-access-warning',
    NotFound: `/404`,
    AddStoreTest: '/test/add-store',
    ProductStatistic: `${basePath}/statistic/products`,
    CustomizeSampleProduct: (productId) => `${basePath}/sample-product/${productId || ':productId'}/customize`,
    DuplicateUserProduct: (productId) => `${basePath}/user-product/${productId || ':productId'}/duplicate`,

    //BasicMore: 'https://printholo.freshdesk.com/support/home',
    BasicMore: 'https://printhlolo.freshdesk.com/support/solutions',
    JoinFanPage: "https://www.facebook.com/groups/printholo",
    ShopifyApp: "https://apps.shopify.com/printholo-1",
    Tracking: (tracking_number) => `/tracking/${tracking_number || ':tracking_number'}`
}
export default Paths
