export const INSTALL_RESPONSE_CODES = {
    INVALID_TOKEN: '1',
    ERROR_INSTALL: '2',
    SUCCESS: '3',
    SUCCESS_NEW_ACCOUNT: '4',
    STORE_EXISTED: '5',
    STORE_EMAIL_EXISTED: '6',
    ALL_STORE_INACTIVE: '7'
}